# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadInsightsConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=10)),
                ('rule_id', models.IntegerField()),
                ('sub_rule_id', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=10)),
                ('versions', models.CharField(max_length=10)),
                ('priority', models.IntegerField(null=True)),
                ('rule_title', models.CharField(max_length=20)),
                ('derived', models.IntegerField(null=True)),
                ('derived_from', models.CharField(max_length=20)),
                ('dt_14764', models.IntegerField(null=True)),
                ('mt_25196', models.IntegerField(null=True)),
                ('mt_26007', models.IntegerField(null=True)),
                ('mt_27905', models.IntegerField(null=True)),
                ('mt_27955', models.IntegerField(null=True)),
                ('mt_28065', models.IntegerField(null=True)),
                ('condition_data', models.CharField(max_length=1000)),
                ('insight', models.CharField(max_length=500)),
            ],
        ),
    ]
