# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileadd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadinsightsconditions',
            name='sub_rule_id',
            field=models.CharField(max_length=10),
        ),
    ]
